---
title: "Introduction to Causal Inference for Data Science"
author: "Mathew Kiang, Zhe Zhang, Monica Alexander"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Introduction
This is a workshop presented to Masters in Data Science student's at Instituto Tecnológico Autónomo de México (ITAM) in March 2017. The slides are free to share, use, modify. We drew heavily from course texts and notes and cited as much as possible at the end of the lectures. 

### Description
New information is being generated and stored at the fastest rate in human history. This has lead to a promise of a “big data” revolution and the belief that fundamental questions about business, government, and biomedical research will finally be answered. Questions like: How much will my Master’s in Data Science degree increasing my earnings? How will a country-wide increase in minimum wage affect the unemployment rate? Does the MMR vaccine cause autism? While certainly helpful, more data by itself is insufficient for answering these important questions. By using methods from social sciences, this workshop is designed to introduce data scientists to causal inference and enable them to ask, investigate, and answer these questions.

### Structure
The first section of the course is focused on understanding the fundamental issues of causal inference, learn a rigorous framework for investigating causal effects, and understand the importance of experimental design. Since experimental design is not always possible in common data science contexts, the second half of the course focuses causal inference techniques that allow for estimation of causal effects by imitating experimental designs using matching, regression, or other sources of exogeneity.

### Topics
1. [Why should we care about causal inference? Motivation, examples, intro to Rubin Causal Model.](./slides/part-01-intro/index.html)
1. [RCTs, Causal DAGs, and the structure of bias](./slides/part-02-rcts-dags/index.html)
1. [Linear regression and bias](./part-03-07/lec_3_linreg_and_biases.html)
1. [Instrumental variables (aka Magic) and Regression Discontinuity](./part-03-07/lec_4_instrumental_variables.html)
1. [Fixed Effects, Difference in differences, and Panel](./part-03-07/lec_5_panel_data.html)
1. [Experimental Design (and a tiny bit on matching)](./part-08-exp-design/index.html)

### Additional topics
1. [Group exercises](./part-03-07/lec_6_class_participation.html)
1. [Talking over examples](./part-03-07/lec_6_examples.html)
1. [Additional topics (we didn't cover)](./part-03-07/lec_7_extensions.html)

### Lecturers
- [Mathew Kiang](https://mathewkiang.com) ([GitHub](https://github.com/mkiang))
- [Zhe Zhang](http://aboutzhe.com) ([GitHub](https://github.com/writezhe))
- [Monica Alexander](http://monicaalexander.com) ([GitHub](https://github.com/MJAlexander))

## Source Code
You can find the source code [this project's GitHub page](https://github.com/mkiang/intro-ci-shortcourse).