---
title: "Causal Inference for Data Science"
subtitle: "ITAM Short Workshop"
author: "Mathew Kiang, Zhe Zhang, Monica Alexander"
date: "March 13, 2017"
output:
  xaringan::moon_reader:
    css: ["custom.css", "./../custom.css", ]
    # In order for the css file to work, you need to set your working directory
    # to one above the slide directory ('./../') and then call moon_reader via
    # `xaringan::inf_mr('./part-01-intro/index.Rmd')`
    # Or just knit it into a browser and it should work immediately.
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
name: inverse
layout: true
class: center, middle, inverse

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

---

# Roadmap

---
layout: false
.left-column[
  ## Roadmap
### For the workshop
]
.right-column[
- **Rubin causal model.** Establish a rigorous framework for evaluating and understanding causality
]
--
.right-column[
- **Experimental designs.** Within this framework, discuss the **ideal** situation for inferring causality, randomized control trials
]
--
.right-column[
- **Confounding and selection.** Ways non-experimental designs can be biased
]
--
.right-column[
- **Methods and application.** Finally, go over methods that mimic experiments in order to infer causality in real-world settings
]

---
.left-column[
  ## Roadmap
  ### For the workshop
  ### For today
]
.right-column[
- **Motivation.** Why do we care about causal inference at all?
]
--
.right-column[
- **Definition.** What is causal inference? 
]
--
.right-column[
- **Rubin causal model.** A framework for evaluating causality
]

---
template: inverse

## Motivation
### Why do we care about causal inference at all?

---
.left-column[
  ## Motivation
  ### Example 1
]
.right-column[
Text here.

- Bullet points

- An example
]

---
.left-column[
  ## Motivation
  ### Example 1
  ### Example 2
]
.right-column[
Text here.

- Bullet points

- An example again
]

---
.left-column[
  ## Motivation
  ### Example 1
  ### Example 2
  ### Example 3
]
.right-column[
Last one.

- Bullet points with more
- Bullet points

- Last example
]

---
template: inverse

## Definition
### What is causal inference?

---
template: inverse

## Rubin causal model
### A framework for evaluating causality

---
class: center, middle
# Thanks!

---
# Sources

---
# Additional Reading