---
title: "Small Group Causal Inference Exercise"
subtitle: "ITAM Short Workshop"
author: "Zhe Zhang, Mathew Kiang, Monica Alexander"
date: "March 16, 2017"
output:
  xaringan::moon_reader:
    css: ["custom.css", "./../custom.css", ]
    # In order for the css file to work, you need to set your working directory
    # to one above the slide directory ('./../') and then call moon_reader via
    # `xaringan::inf_mr('./part-01-intro/index.Rmd')`
    # Or just knit it into a browser and it should work immediately.
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

# Group Brainstorm Exercise

Possible Orgs:  
{Facebook, Civis Analytics, Chase Bank,  
Kaiser Chain of Hospitals, Health Department of Government of Mexico,  
Urban Housing Program, Insurance Company,  
Microfinance Platform, Agricultural Policy,
Google's Search Team, Amazon's }

Questions:  
1. Identify two causal questions of interest
2. Identify the ideal RCT to run (how to get participants, how to randomize, how to test)
3. Describe the ideal observational dataset
4. Describe a more realistic observational data, and how you might identify a causal effect of interest
5. Discuss with class (3-4 mins + time for class discussion & feedback)

---
# Additional Topics

---
# Papers With Interesting Casual Identification (Part 1)

*discussed very briefly in class*

- Gentzkow, M. (2007). Valuing new goods in a model with complementarity: Online newspapers. The American Economic Review, 97(3), 713-744.
- Greenstone, M., Hornbeck, R., & Moretti, E. (2010). Identifying agglomeration spillovers: Evidence from winners and losers of large plant openings. Journal of Political Economy, 118(3), 536-598.
- Jensen, R. (2007). The digital provide: Information (technology), market performance, and welfare in the South Indian fisheries sector. The quarterly journal of economics, 122(3), 879-924.
- Kabra, Belavina, and Girota (Working Paper), "The Efficacy of Incentives in Scaling Marketplaces"
- Khern-am-nuai, Warut and Ghasemkhani, Hossein and Kannan, Karthik Natarajan, How Questions and Answers Shape Online Marketplaces: The Case of Amazon Answer (June 10, 2016). Available at SSRN: https://ssrn.com/abstract=2794149

---
# Papers With Interesting Casual Identification (Part 2)

*discussed very briefly in class*

- Luca, M. (2016). Reviews, reputation, and revenue: The case of Yelp. com.
- Muchnik, L., Aral, S., & Taylor, S. J. (2013). Social influence bias: A randomized experiment. Science, 341(6146), 647-651.
- Seamans, R., & Zhu, F. (2013). Responses to entry in multi-sided markets: The impact of Craigslist on local newspapers. Management Science, 60(2), 476-493.
- Smith, M. D., & Telang, R. (2009). Competing with free: the impact of movie broadcasts on DVD sales and internet piracy 1. mis Quarterly, 33(2), 321-338.
- Xu, K., Chan, J., Ghose, A., & Han, S. P. (2016). Battle of the channels: The impact of tablets on digital commerce. Management Science.
- Zervas, G., Proserpio, D., & Byers, J. W. (2014). The rise of the sharing economy: Estimating the impact of Airbnb on the hotel industry. Journal of Marketing Research.